FROM golang:1.19 as builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCJ=amd64 go build -o server -ldflags="-w -s" .

FROM scratch
COPY --from=builder /app/server /server
EXPOSE 8080 8080
ENTRYPOINT ["/server"]